# TODO: Replace this with a shell script that mimics dev behavior
FROM httpd:2.4-alpine

# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
#     sudo \
#     python3 \
#     python3-pip \
#     vim \
#     emacs \
#     curl

# RUN useradd -mk /etc/skel/ admin
# RUN usermod --shell "/bin/bash" admin
# RUN echo "admin:password" | chpasswd

# CMD ["python3 -m http.server 80"]