version: "3.9"

services:
  external-vpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1195:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/external:/etc/openvpn
    networks:
      external-net:
        ipv4_address: "10.44.44.3"

  internal-vpn:
    image: kylemanna/openvpn
    hostname: vpn.hattitude.biz
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/internal:/etc/openvpn
    networks:
      internal-net:
        ipv4_address: "10.10.10.3"

  kali:
    build: docker/kali
    hostname: kali
    ports:
      - "22:22"
    networks:
      external-net:
        ipv4_address: "10.44.44.4"
    dns:
      - "10.44.44.2"

  proda:
    build: docker/ubuntu-base
    hostname: web1-10-10-10-6
    environment:
      - USERS=webadmin:010101;user:888888;bob:a1b2c3;test:changeme;root:hattitude
    expose:
      - "0-65535"
    volumes:
      - ./volumes/production_website:/var/www/html/
      - ./files/ssh/root/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/ssh/alice/id_rsa:/home/alice/.ssh/id_rsa
      - ./files/service/apache2/run:/etc/service/apache2/run
      - ./files/service/apache2/apache2.conf:/etc/apache2/apache2.conf
    networks:
      internal-net:
        ipv4_address: "10.10.10.6"
      external-net:
        ipv4_address: "10.44.44.12"

  prodb:
    build: docker/ubuntu-base
    hostname: web2-10-10-10-7
    environment:
      - USERS=webadmin:010101;user:888888;alice:gizmo1;root:hattitude
    expose:
      - "0-65535"
    volumes:
      - ./volumes/reviews:/var/www/html/
      - ./files/ssh/root/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/apache2/run:/etc/service/apache2/run
      - ./files/service/apache2/apache2.conf:/etc/apache2/apache2.conf
    networks:
      internal-net:
        ipv4_address: "10.10.10.7"
      external-net:
        ipv4_address: "10.44.44.13"

  prodc:
    build: docker/ubuntu-base
    hostname: db-10-10-10-8
    environment:
      - USERS=dbadmin:dbaccess;sysadmin:friend;alice:gizmo1;test:changeme;root:hattitude
    expose:
      - "0-65535"
    volumes:
      - ./files/ssh/root/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/mysql/run:/etc/service/mysql/run
      - ./files/service/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./files/service/mysql/init_db.sh:/etc/init_db.sh
      - ./volumes/database:/opt/mysql/mysql/data
    networks:
      internal-net:
        ipv4_address: "10.10.10.8"

  inta:
    build: docker/ubuntu-base
    hostname: docs-10-10-10-9
    environment:
      - USERS=sysadmin:friend;bob:a1b2c3;user:letmein;root:hattitude
    expose:
      - "0-65535"
    volumes:
      - ./volumes/internal_wiki:/var/www/html/
      - ./files/ssh/root/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/apache2/run:/etc/service/apache2/run
    networks:
      internal-net:
        ipv4_address: "10.10.10.9"

  dns:
    hostname: dns
    image: technitium/dns-server:latest
    ports:
      - "5380:5380/tcp" #DNS web console
      - "53/tcp" #DNS service
      - "53/udp" #DNS service

    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD=swordfish
      - DNS_SERVER_FORWARDERS=1.1.1.1, 8.8.8.8 #Comma separated list of forwarder addresses.
    volumes:
      - ./volumes/config:/etc/dns/config
    # sysctls:
    #   - net.ipv4.ip_local_port_range=1024 65000
    networks:
      internal-net:
        ipv4_address: "10.10.10.2"
      external-net:
        ipv4_address: "10.44.44.2"
  
networks:
  internal-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

  external-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.44.44.0/24
          gateway: 10.44.44.1