version: "3.9"

services:
  external-vpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/external:/etc/openvpn
    networks:
      - external-net

  internal-vpn:
    image: kylemanna/openvpn
    hostname: vpn.hattitude.biz
    cap_add:
      - NET_ADMIN
    ports:
      - "1195:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/internal:/etc/openvpn
    networks:
      - internal-net

  kali:
    build: docker/kali
    ports:
      - "22:22"
    networks:
      - external-net

  proda:
    build: docker/ubuntu-base
    hostname: proda-10-10-10-6
    environment:
      - USERS=admin:admin;devan:cheese
    ports:
      - "8000:80"
    expose:
      - "0-65535"
    volumes:
      - ./volumes/production_website:/var/www/html/
      - ./files/ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/apache2/run:/etc/service/apache2/run
      - ./files/service/apache2/apache2.conf:/etc/apache2/apache2.conf
    networks:
      internal-net:
        ipv4_address: "10.10.10.6"
      external-net:
        ipv4_address: "10.44.44.12"

  prodb:
    build: docker/ubuntu-base
    hostname: prodb-10-10-10-7
    environment:
      - USERS=admin:admin;devan:cheese
    expose:
      - "0-65535"
    volumes:
      - ./volumes/feedback:/var/www/html/
      - ./files/ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/apache2/run:/etc/service/apache2/run
      - ./files/service/apache2/apache2.conf:/etc/apache2/apache2.conf
    networks:
      internal-net:
        ipv4_address: "10.10.10.7"
      external-net:
        ipv4_address: "10.44.44.13"

  prodc:
    build: docker/ubuntu-base
    hostname: prodc-10-10-10-8
    environment:
      - USERS=admin:admin;devan:cheese;dbadmin:dbadmin
    expose:
      - "0-65535"
    volumes:
      - ./volumes/production_website:/var/www/html/
      - ./files/ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/mysql/run:/etc/service/mysql/run
      - ./volumes/database:/opt/mysql/mysql/data
    networks:
      internal-net:
        ipv4_address: "10.10.10.8"

  inta:
    build: docker/ubuntu-base
    hostname: inta-10-10-10-9
    environment:
      - USERS=admin:admin;devan:cheese
    expose:
      - "0-65535"
    volumes:
      - ./volumes/internal_wiki:/var/www/html/
      - ./files/ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ./files/service/apache2/run:/etc/service/apache2/run
    networks:
      internal-net:
        ipv4_address: "10.10.10.9"

  # dns:
  #   build: docker/ubuntu-base
  #   hostname: proda-10-10-10-2
  #   environment:
  #     - USERS=admin:admin;devan:cheese
  #   expose:
  #     - "0-65535"
  #   volumes:
  #     - ./files/ssh/id_rsa.pub:/root/.ssh/authorized_keys
  #   networks:
  #     internal-net:
  #       ipv4_address: "10.10.10.2"
  #     external-net:
  #       ipv4_address: "10.44.44.2"
  
networks:
  internal-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

  external-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.44.44.0/24
          gateway: 10.44.44.1