version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    networks:
      - internal
      - external

  external-vpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/external:/etc/openvpn
    networks:
      - external

  internal-vpn:
    image: kylemanna/openvpn
    hostname: vpn.hattitude.biz
    cap_add:
      - NET_ADMIN
    ports:
      - "1195:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/internal:/etc/openvpn
    networks:
      - internal

  kali:
    build: docker/kali
    ports:
      - "22:22"
    networks:
      - external

  monitoring:
    build: docker/monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./files/ssh/id_rsa:/root/.ssh/id_rsa
    networks:
      - internal

  proda:
    build: docker/ubuntu-base
    hostname: "ip-10-24-34-0.us-west-2.compute.internal"
    environment:
      - USERS=admin:admin;bob:cheese
    expose:
      - "0-65535"
    volumes:
      - ./volumes/production_website:/var/www/html/
      - ./files/ssh/id_rsa.pub:/root/.ssh/authorized_keys
    networks:
      - internal
      - external
  
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.34.3.0/24
          gateway: 10.34.3.1