# This is the base image for any Ubuntu server which the students may get command-line access to.
# It includes a number of common tools they would expect to find on an Ubuntu machine.
FROM phusion/baseimage:jammy-1.0.1

RUN apt-get update

# Core tools
RUN apt install -y \
    sudo \
    coreutils

# Python
RUN apt install -y \
    python3 \
    python3-pip

# Networking
RUN DEBIAN_FRONTEND=noninteractive apt install -y \
    net-tools \
    curl \
    wget \
    netcat \
    nmap

# Editors
RUN apt install -y \
    vim \
    emacs \
    nano

# Flavor
RUN apt install -y \
    fortune \
    cowsay

# Telnet
RUN apt install -y telnetd

# Apache and PHP
RUN apt install -y apache2
RUN apt install -y php libapache2-mod-php

# MySQL
RUN apt install -y mysql-server

# Create utmp so that `w`, `who`, `users`, etc work
RUN touch /run/utmp
RUN chown root:utmp /run/utmp; chmod g+w /run/utmp

# Generate SSH key
RUN ssh-keygen -A
# RUN ssh-keygen -P "" -t dsa -f /etc/ssh/ssh_host_dsa_key

RUN apt install -y php8.1-mysql iputils-ping

# Clean up APT when done.
# RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Add config files
COPY ./config/sshd_config /etc/ssh/sshd_config

# Add init scripts
ADD ./init /etc/my_init.d

CMD ["/sbin/my_init"]