FROM kalilinux/kali-rolling

RUN apt update

RUN apt install -y openssh-server
RUN apt install -y nmap
RUN apt install -y sudo

RUN mkdir /run/sshd
COPY ./sshd_config /etc/ssh/sshd_config

RUN useradd -mk /etc/skel/ "student"
RUN usermod --shell "/bin/bash" "student"
RUN echo "student:CSCI-3403!" | chpasswd

RUN touch /home/student/.hushlogin
RUN apt install 

CMD ["/usr/sbin/sshd", "-D"]