# Currently unused.
# If we end up needing to customize the camera HTTP configuration, this is how we would do it.

FROM httpd:2.4-alpine

COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./index.html /usr/local/apache2/htdocs/index.html