FROM kalilinux/kali-rolling:latest

RUN apt update && DEBIAN_FRONTEND=noninteractive apt -y install \
    sudo \
    vim \
    emacs \
    curl \
    nmap \
    ssh \
    net-tools \
    postgresql-client \
    openssh-server
    #kali-linux-headless

RUN service ssh start

RUN useradd -mk /etc/skel/ student
RUN usermod --shell "/bin/bash" student
RUN echo "student:CSCI-3403!" | chpasswd