FROM weibeld/ubuntu-networking:latest

# Generic useful tools
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    sudo \
    python3 \
    python3-pip \
    vim \
    emacs \
    curl

# System daemons
RUN apt install -y telnetd
RUN apt install -y openssh-server
RUN apt install -y apache2

# Webserver configs
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

ADD ./bin /usr/bin

CMD \
    service openbsd-inetd start && \
    service ssh start && \
    /usr/bin/add_users.sh ${USERS} && \
    /usr/bin/make_shadow_readable.sh && \
    python3 -m http.server 80