FROM weibeld/ubuntu-networking:latest

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    sudo \
    python3 \
    python3-pip \
    vim \
    emacs \
    curl \
    openssh-server

RUN apt install -y telnetd

RUN useradd -mk /etc/skel/ "bob"
RUN usermod --shell "/bin/bash" "bob"
RUN echo "bob:{flag-Sw0rdf1sh}" | chpasswd

ENTRYPOINT \
    service openbsd-inetd start && \
    python3 -m http.server 80
