FROM weibeld/ubuntu-networking:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    sudo \
    python3 \
    python3-pip \
    vim \
    emacs \
    curl \
    openssh-server

RUN systemctl enable ssh
COPY index.html .

RUN useradd -mk /etc/skel/ admin
RUN usermod --shell "/bin/bash" admin
RUN echo "admin:password" | chpasswd

CMD ["python3", "-m", "http.server", "80"]